#pragma once

#include "common.h"

#include <ktl_shared.h>

#include <shared_mutex>
#include <string>

// GUID generated by VS, hopefully actually globally unique.
static const ktl::unicode_string_view KTL_TEST_DEVICE_NAME{ L"\\DosDevices\\" KTL_TEST_DEVICE_USERMODE_NAME };

struct KtlGlobalState
{
    ktl::unicode_string DeviceName;
    ktl::shared_mutex RwLock;
};

typedef struct _KTL_TEST_DEVICE_EXTENSION
{
    HANDLE FileHandle;
} KTL_TEST_DEVICE_EXTENSION, *PKTL_TEST_DEVICE_EXTENSION;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(KTL_TEST_DEVICE_EXTENSION, GetKtlTestDeviceExtension);

typedef struct _KTL_TEST_IOCTL_CONTEXT
{
    WDFMEMORY UsermodeIn;
    WDFMEMORY UsermodeOut;
} KTL_TEST_IOCTL_CONTEXT, *PKTL_TEST_IOCTL_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(KTL_TEST_IOCTL_CONTEXT, GetKtlTestIoctlContext);