#pragma once

#define KTL_TEST_DEVICE_USERMODE_NAME L"{A826018B-76AD-492A-AB1B-9E5F7C1FAE02}"

#define KTLTEST_TYPE 0xBF40UL

#define IOCTL_KTLTEST_METHOD_ALGORITHM_TEST \
    CTL_CODE( KTLTEST_TYPE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS  )

#define IOCTL_KTLTEST_METHOD_LIST_TEST \
    CTL_CODE( KTLTEST_TYPE, 0x802, METHOD_NEITHER , FILE_ANY_ACCESS  )

#define IOCTL_KTLTEST_METHOD_MEMORY_TEST \
    CTL_CODE( KTLTEST_TYPE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS  )

#define IOCTL_KTLTEST_METHOD_SET_TEST \
    CTL_CODE( KTLTEST_TYPE, 0x804, METHOD_NEITHER , FILE_ANY_ACCESS  )

#define IOCTL_KTLTEST_METHOD_VECTOR_TEST \
    CTL_CODE( KTLTEST_TYPE, 0x805, METHOD_NEITHER , FILE_ANY_ACCESS  )